log:
  level: ${{ uci -q get mosdns.mosdns.loglv }}
  file: ${{ uci -q get mosdns.mosdns.logfile }}

plugin:
  - tag: main_server
    type: server
    args:
      entry:
        - _no_ecs
        - lazy_cache
        - _prefer_ipv4
        - _single_flight
        - main_sequence
      server:
        - protocol: udp
          addr: ":${{ uci -q get mosdns.mosdns.listen_port }}"
        - protocol: tcp
          addr: ":${{ uci -q get mosdns.mosdns.listen_port }}"

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - query_is_hosts_domain
        - query_is_redirect_domain
        - if:
            - query_is_whitelist_domain
          exec:
            - forward_local
            - _return
        - if:
            - query_is_blocklist_domain
            - query_is_ad_domain
            - qtype65
          exec:
            - _block_with_nxdomain
            - _return
        - if:
            - query_is_local_domain
            - "!_query_is_common"
          exec:
            - forward_local
            - _return
        - if:
            - query_is_non_local_domain
          exec:
            - forward_remote
            - _return
        - primary:
            - forward_local
            - if:
                - "!response_has_local_ip"
              exec:
                - _drop_response
          secondary:
            - forward_remote
          fast_fallback: 150
          always_standby: true

  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: ${{ ./dns.sh 0 }}
        - addr: ${{ ./dns.sh 1 }}

  - tag: query_is_whitelist_domain
    type: query_matcher
    args:
      domain:
        - "ext:./whitelist.txt"

  - tag: query_is_blocklist_domain
    type: query_matcher
    args:
      domain:
        - "ext:/etc/mosdns/rule/blocklist.txt"

  - tag: query_is_hosts_domain
    type: hosts
    args:
      hosts:
        - "ext:/etc/mosdns/rule/hosts.txt"

  - tag: query_is_redirect_domain
    type: redirect
    args:
      rule:
        - "ext:/etc/mosdns/rule/redirect.txt"

  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: ${{ uci -q get mosdns.mosdns.remote_dns1 }}
        - addr: ${{ uci -q get mosdns.mosdns.remote_dns2 }}

  - tag: lazy_cache
    type: cache
    args:
      size: 512000
      lazy_cache_ttl: 259200

  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - "ext:/usr/share/v2ray/geosite.dat:cn"
        - "ext:/usr/share/v2ray/geosite.dat:apple-cn"

  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - "ext:/usr/share/v2ray/geosite.dat:geolocation-!cn"

  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - "ext:/usr/share/v2ray/geoip.dat:cn"

  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - "ext:./serverlist.txt"

  - tag: qtype65
    type: query_matcher
    args:
      qtype: [65]
