#!/bin/sh /etc/rc.common
# Copyright (C) 2020 IrineSistiana

START=99
USE_PROCD=1

#####  ONLY CHANGE THIS BLOCK  ######
PROG=/usr/bin/mosdns/mosdns # where is mosdns
RES_DIR=/etc/mosdns/ # resource dir / working dir / the dir where you store ip/domain lists
CONF=./config.yaml   # where is the config file, it can be a relative path to $RES_DIR
CONFIGURATION=MosDNS
#####  ONLY CHANGE THIS BLOCK  ######

service_triggers()
{
    procd_add_reload_trigger "CONFIGURATION"
}

reload_service()
{
	stop
    start
}

start_service() {
   # Reading config
   config_load "${CONFIGURATION}"
   local enabled

  config_get_bool enabled MosDNS enabled 0

  if [ "$enabled" -eq 0 ]; then
	echo "MosDNS has turned off"
	return 1
  fi
	
  procd_open_instance
  procd_set_param command $PROG -dir $RES_DIR -c $CONF

  procd_set_param user root
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
  procd_close_instance
  echo "MosDNS turn on"
  echo "enabled="$enabled""
}

stop_service()
{
  config_load "${CONFIGURATION}"
  local enabled
 
  config_get_bool enabled MosDNS enabled 0
  killall -q mosdns
  echo "MosDNS turn off"
  echo "enabled="$enabled""
}